import { StyleSheet } from 'react-native';
import { ColorPalette } from '../../theme/colors';
import { spacing } from '../../theme/spacing';
import { typography } from '../../theme/typography';

export const createRequestProjectFormStyles = (palette: ColorPalette, fontMode: string) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: palette.background,
    },
    headerInScroll: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: spacing.lg,
      paddingVertical: spacing.md,
      backgroundColor: palette.background,
    },
    titleInScroll: {
      fontSize: typography.xl3,
      fontWeight: '700',
      color: palette.text,
      fontFamily: fontMode === 'dyslexic' ? 'OpenDyslexic-Bold' : 'System',
    },
    titleAccentInScroll: {
      color: palette.primary,
    },
    helpBox: {
      backgroundColor: '#FEF3C7',
      borderWidth: 1,
      borderColor: '#FCD34D',
      borderRadius: 12,
      padding: spacing.md,
      marginHorizontal: spacing.lg,
      marginBottom: spacing.md,
      flexDirection: 'row',
      alignItems: 'flex-start',
    },
    helpIcon: {
      marginRight: spacing.sm,
      marginTop: 2,
    },
    helpContent: {
      flex: 1,
    },
    helpTitle: {
      fontSize: typography.base,
      fontWeight: '600',
      color: '#92400E',
      marginBottom: spacing.xs,
      fontFamily: fontMode === 'dyslexic' ? 'OpenDyslexic-Bold' : 'System',
    },
    helpText: {
      fontSize: typography.sm,
      color: '#92400E',
      lineHeight: 20,
      fontFamily: fontMode === 'dyslexic' ? 'OpenDyslexic-Regular' : 'System',
    },
    form: {
      backgroundColor: palette.background,
      paddingHorizontal: spacing.lg,
      paddingBottom: spacing.xl,
    },
    section: {
      backgroundColor: palette.background,
      borderRadius: 16,
      padding: spacing.lg,
      marginBottom: spacing.md,
      borderWidth: 1,
      borderColor: palette.grayLight,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 2,
    },
    sectionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: spacing.md,
      paddingBottom: spacing.sm,
      borderBottomWidth: 2,
      borderBottomColor: '#E5E7EB',
    },
    sectionIcon: {
      width: 32,
      height: 32,
      borderRadius: 8,
      backgroundColor: '#ECFDF5',
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: spacing.sm,
    },
    sectionTitleContainer: {
      flex: 1,
    },
    sectionTitle: {
      fontSize: typography.lg,
      fontWeight: '700',
      color: palette.text,
      fontFamily: fontMode === 'dyslexic' ? 'OpenDyslexic-Bold' : 'System',
    },
    sectionSubtitle: {
      fontSize: typography.sm,
      color: palette.textSecondary,
      marginTop: 2,
      fontFamily: fontMode === 'dyslexic' ? 'OpenDyslexic-Regular' : 'System',
    },
    field: {
      marginBottom: spacing.md,
    },
    label: {
      fontSize: typography.base,
      fontWeight: '600',
      color: palette.text,
      marginBottom: spacing.xs,
      fontFamily: fontMode === 'dyslexic' ? 'OpenDyslexic-Bold' : 'System',
    },
    requiredIndicator: {
      color: '#DC2626',
    },
    input: {
      backgroundColor: palette.background,
      borderWidth: 1,
      borderColor: '#D1D5DB',
      borderRadius: 12,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm + 2,
      fontSize: typography.base,
      color: palette.text,
      fontFamily: fontMode === 'dyslexic' ? 'OpenDyslexic-Regular' : 'System',
    },
    inputFocused: {
      borderColor: palette.primary,
      borderWidth: 2,
    },
    textArea: {
      height: 120,
      textAlignVertical: 'top',
      paddingTop: spacing.sm + 2,
    },
    infoBox: {
      backgroundColor: '#FEF3C7',
      borderWidth: 1,
      borderColor: '#FCD34D',
      borderRadius: 8,
      padding: spacing.sm,
      marginBottom: spacing.sm,
      flexDirection: 'row',
      alignItems: 'center',
    },
    infoText: {
      flex: 1,
      fontSize: typography.sm,
      color: '#92400E',
      marginLeft: spacing.xs,
      fontFamily: fontMode === 'dyslexic' ? 'OpenDyslexic-Regular' : 'System',
    },
    buttonsContainer: {
      flexDirection: 'row',
      gap: spacing.sm,
      marginTop: spacing.lg,
      paddingHorizontal: spacing.lg,
      paddingBottom: spacing.md,
    },
    clearButton: {
      flex: 1,
      backgroundColor: '#F3F4F6',
      paddingVertical: spacing.md,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: '#D1D5DB',
    },
    clearButtonText: {
      fontSize: typography.base,
      fontWeight: '600',
      color: '#374151',
      fontFamily: fontMode === 'dyslexic' ? 'OpenDyslexic-Bold' : 'System',
    },
    submitButton: {
      flex: 1,
      backgroundColor: palette.primary,
      paddingVertical: spacing.md,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: palette.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 4,
    },
    submitButtonText: {
      fontSize: typography.base,
      fontWeight: '700',
      color: palette.onPrimary,
      fontFamily: fontMode === 'dyslexic' ? 'OpenDyslexic-Bold' : 'System',
    },
    errorText: {
      fontSize: typography.sm,
      color: '#DC2626',
      marginTop: spacing.xs,
      fontFamily: fontMode === 'dyslexic' ? 'OpenDyslexic-Regular' : 'System',
    },

    deadlineWarningBox: {
    marginTop: 10,
    padding: 12,
    borderRadius: 10,
    backgroundColor: '#FEF3C7',
    borderWidth: 1,
    borderColor: '#F59E0B',
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 8,
  },

  deadlineWarningText: {
    color: '#92400E',
    fontSize: 14,
  },

  });